"""
conditions.py — Think AI Live Condition Monitor
=================================================
Responsibility:  Store, track, and evaluate the Go/Stop/Review conditions
                 that the Refiner generates for every decision. Turns a
                 static analysis snapshot into a living decision system.

The problem this solves
-----------------------
Without conditions.py, the Go/Stop/Review conditions inside VerdictBox
are printed once and forgotten. A company makes a decision on Monday,
a stop condition fires on Wednesday, and nobody knows.

This module makes conditions actionable:
  1. register_conditions()  — called after every /decide, stores conditions
  2. check_conditions()     — evaluates each condition's current status
  3. get_active_conditions() — returns everything live for a company
  4. acknowledge_condition() — user marks a fired condition as seen
  5. request_reanalysis()    — escalates a fired stop condition back through
                               the full route → refine → format_for_ui pipeline

How conditions are evaluated
-----------------------------
Conditions are free-text strings generated by the Refiner (e.g.
"Go ahead if churn rate is below 5%"). Full automated evaluation
requires live data feeds — that's marketplace.py's job.

Until marketplace.py is built, conditions.py evaluates in two ways:
  * Time-based triggers  — "Review again in 30 days" → fires automatically
  * Manual acknowledgement — user reads conditions and marks them
  * LLM-assisted spot-check — a lightweight LLM call checks if a
    condition MIGHT have changed based on context the user provides

This is the honest architecture: useful now, fully automated later.

How it connects (zero edits to existing files)
-----------------------------------------------
  main.py  →  register_conditions()   after update_memory()
  main.py  →  new /conditions endpoints
  conditions.py imports UIDecisionPayload, VerdictBox from refiner/output
  memory.py is NOT imported — conditions has its own storage to keep
  concerns separated and allow independent scaling.

Storage
-------
  Default  : JSON files in conditions_store/ (same pattern as memory.py)
  Production: Swap _ConditionBackend for Redis / Postgres via env var.

Security
--------
  * company_id SHA-256 hashed in all file paths — no PII on disk
  * decision_id validated before any write
  * Condition text sanitised before LLM spot-check calls
  * Per-company asyncio locks on all writes
  * LLM spot-check is read-only — never modifies a decision

Usage
-----
    from conditions import register_conditions, get_active_conditions

    # After /decide (called from main.py)
    await register_conditions(company_id, decision_id, query, verdict_box)

    # Polling or webhook — check what's fired
    report = await get_active_conditions(company_id)
"""

from __future__ import annotations

from dotenv import load_dotenv
load_dotenv()   # ensures .env is loaded before AsyncOpenAI client is created

import asyncio
import hashlib
import json
import logging
import os
import random
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Literal

from openai import AsyncOpenAI, APIStatusError, APITimeoutError
from pydantic import BaseModel, Field, field_validator

# ── Import shared contracts — zero re-definition ──────────────────────────
from router import UserContext
from refiner import VerdictBox

# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────

_STORE_DIR          = Path(os.getenv("THINK_AI_CONDITIONS_DIR",  "conditions_store"))
_MAX_RECORDS        = int(os.getenv("THINK_AI_CONDITIONS_MAX",   "200"))   # per company
_LOCK_TIMEOUT_SEC   = float(os.getenv("THINK_AI_CONDITIONS_LOCK", "5"))
_MAX_RETRIES        = int(os.getenv("THINK_AI_REFINER_RETRIES",   "3"))    # reuse same env var
_SPOT_CHECK_MODEL   = os.getenv("THINK_AI_CONDITIONS_MODEL",     "gpt-4o-mini")
_SPOT_CHECK_TIMEOUT = float(os.getenv("THINK_AI_CONDITIONS_TIMEOUT", "20"))
_AUTO_REVIEW_DAYS   = int(os.getenv("THINK_AI_CONDITIONS_REVIEW_DAYS", "30"))
_CONDITIONS_VERSION = "1.0.0"

_client: AsyncOpenAI | None = None

def _get_client() -> AsyncOpenAI:
    global _client
    if _client is None:
        load_dotenv()
        _client = AsyncOpenAI(
            api_key=os.getenv("OPENAI_API_KEY"),
            base_url=os.getenv("OPENAI_BASE_URL") or None,
            timeout=_SPOT_CHECK_TIMEOUT,
            max_retries=0,
        )
    return _client

# ─────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger("think-ai.conditions")

# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────

ConditionKind   = Literal["go", "stop", "review"]
ConditionStatus = Literal[
    "active",       # condition is live, not yet evaluated
    "fired",        # condition has triggered — needs attention
    "acknowledged", # user has seen the alert
    "cleared",      # condition is no longer relevant (manual or auto)
    "expired",      # decision is old enough that conditions are stale
]

# Stop conditions are always urgent.
# Go conditions: if one fails, the decision turns Orange.
# Review triggers: fire on a schedule or when context changes.
STATUS_PRIORITY: dict[ConditionStatus, int] = {
    "fired":        1,
    "active":       2,
    "acknowledged": 3,
    "cleared":      4,
    "expired":      5,
}


# ─────────────────────────────────────────────
# SCHEMAS
# ─────────────────────────────────────────────

class ConditionRecord(BaseModel):
    """One stored condition attached to a decision."""

    condition_id:   str                  # SHA-256 of decision_id + kind + text
    decision_id:    str
    company_id:     str
    query_preview:  str                  # first 80 chars of the original query
    kind:           ConditionKind
    text:           str                  # the raw condition string from Refiner
    status:         ConditionStatus      = "active"
    created_utc:    str
    last_checked_utc: str | None         = None
    fired_utc:      str | None           = None
    acknowledged_utc: str | None         = None
    cleared_utc:    str | None           = None
    expires_utc:    str                  # auto-set to created + _AUTO_REVIEW_DAYS
    spot_check_note: str | None          = None  # LLM's last assessment
    reanalysis_requested: bool           = False

    @field_validator("kind")
    @classmethod
    def validate_kind(cls, v: str) -> str:
        if v not in ("go", "stop", "review"):
            return "review"
        return v

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        valid = ("active", "fired", "acknowledged", "cleared", "expired")
        return v if v in valid else "active"


class CompanyConditionStore(BaseModel):
    """All conditions for one company — what gets written to disk."""
    company_id_hash: str
    version:         str = _CONDITIONS_VERSION
    records:         list[ConditionRecord] = Field(default_factory=list)
    last_updated_utc: str


class ConditionReport(BaseModel):
    """
    Client-facing report returned by get_active_conditions().
    Safe to send directly to the frontend.
    """
    company_id:       str
    total_active:     int
    total_fired:      int
    total_acknowledged: int
    urgent:           list[ConditionRecord]   # fired stop conditions
    needs_review:     list[ConditionRecord]   # fired review triggers
    go_conditions:    list[ConditionRecord]   # go conditions (active or fired)
    generated_utc:    str


class SpotCheckRequest(BaseModel):
    """Body for POST /conditions/spot-check."""
    company_id:   str = Field(min_length=1, max_length=128)
    condition_id: str = Field(min_length=1, max_length=64)
    user_update:  str = Field(
        min_length=3, max_length=1000,
        description=(
            "What the user knows right now that's relevant to this condition. "
            "e.g. 'Our churn rate went up to 7% this month.'"
        ),
    )
    context: dict[str, Any] | None = None


class SpotCheckResult(BaseModel):
    """Result of an LLM-assisted condition spot-check."""
    condition_id:    str
    condition_text:  str
    kind:            ConditionKind
    user_update:     str
    assessment:      Literal["likely_fired", "likely_clear", "uncertain"]
    reasoning:       str
    recommended_action: str
    new_status:      ConditionStatus   # what we set the condition to after this check


# ─────────────────────────────────────────────
# CONCURRENCY GUARD
# ─────────────────────────────────────────────

_write_locks: dict[str, asyncio.Lock] = {}


def _get_lock(company_id: str) -> asyncio.Lock:
    if company_id not in _write_locks:
        _write_locks[company_id] = asyncio.Lock()
    return _write_locks[company_id]


# ─────────────────────────────────────────────
# STORAGE BACKEND
# ─────────────────────────────────────────────

def _company_hash(company_id: str) -> str:
    return hashlib.sha256(company_id.encode()).hexdigest()


def _store_path(company_id: str) -> Path:
    return _STORE_DIR / f"{_company_hash(company_id)}.json"


def _ensure_store_dir() -> None:
    _STORE_DIR.mkdir(parents=True, exist_ok=True)
    gitignore = _STORE_DIR / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text("*\n")


async def _read_store(company_id: str) -> CompanyConditionStore | None:
    path = _store_path(company_id)
    if not path.exists():
        return None
    try:
        raw = await asyncio.to_thread(path.read_text, encoding="utf-8")
        return CompanyConditionStore.model_validate_json(raw)
    except Exception as e:
        logger.error(
            "Conditions read error | company_hash=%s | %s",
            _company_hash(company_id)[:12], e,
        )
        return None


async def _write_store(company_id: str, store: CompanyConditionStore) -> bool:
    _ensure_store_dir()
    path = _store_path(company_id)
    # Cap total records — drop oldest cleared/expired first
    if len(store.records) > _MAX_RECORDS:
        droppable = [
            r for r in store.records
            if r.status in ("cleared", "expired", "acknowledged")
        ]
        droppable.sort(key=lambda r: r.created_utc)
        to_drop = set(r.condition_id for r in droppable[:len(store.records) - _MAX_RECORDS])
        store.records = [r for r in store.records if r.condition_id not in to_drop]

    try:
        await asyncio.to_thread(
            path.write_text,
            store.model_dump_json(indent=2),
            encoding="utf-8",
        )
        return True
    except Exception as e:
        logger.error(
            "Conditions write error | company_hash=%s | %s",
            _company_hash(company_id)[:12], e,
        )
        return False


def _new_store(company_id: str) -> CompanyConditionStore:
    return CompanyConditionStore(
        company_id_hash=_company_hash(company_id),
        records=[],
        last_updated_utc=datetime.now(timezone.utc).isoformat(),
    )


# ─────────────────────────────────────────────
# INTERNAL HELPERS
# ─────────────────────────────────────────────

def _condition_id(decision_id: str, kind: str, text: str) -> str:
    """Deterministic, stable ID for one condition."""
    raw = f"{decision_id}:{kind}:{text.strip().lower()}"
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


def _expires_utc(days: int = _AUTO_REVIEW_DAYS) -> str:
    return (datetime.now(timezone.utc) + timedelta(days=days)).isoformat()


def _check_expiry(record: ConditionRecord) -> ConditionRecord:
    """If the condition's expiry has passed and it's still active, mark expired."""
    if record.status not in ("active", "fired"):
        return record
    try:
        expires = datetime.fromisoformat(record.expires_utc)
        if datetime.now(timezone.utc) > expires:
            record.status = "expired"
            logger.info(
                "Condition expired | id=%s | kind=%s",
                record.condition_id, record.kind,
            )
    except Exception:
        pass
    return record


def _build_records_from_verdict(
    company_id:   str,
    decision_id:  str,
    query:        str,
    verdict:      VerdictBox,
) -> list[ConditionRecord]:
    """
    Converts a VerdictBox's three condition lists into ConditionRecord objects.
    Deduplicates by condition_id so re-registering the same decision is safe.
    """
    now = datetime.now(timezone.utc).isoformat()
    records: list[ConditionRecord] = []

    # Review triggers expire sooner — they're time-sensitive by nature
    expiry_days: dict[str, int] = {
        "go":     _AUTO_REVIEW_DAYS,
        "stop":   _AUTO_REVIEW_DAYS * 2,    # stop conditions stay longer
        "review": max(7, _AUTO_REVIEW_DAYS // 2),
    }

    for kind, texts in [
        ("go",     verdict.go_conditions),
        ("stop",   verdict.stop_conditions),
        ("review", verdict.review_triggers),
    ]:
        for text in texts:
            if not text or not text.strip():
                continue
            cid = _condition_id(decision_id, kind, text)
            records.append(ConditionRecord(
                condition_id=cid,
                decision_id=decision_id,
                company_id=company_id,
                query_preview=query[:80],
                kind=kind,
                text=text.strip(),
                status="active",
                created_utc=now,
                expires_utc=_expires_utc(expiry_days[kind]),
            ))

    return records


# ─────────────────────────────────────────────
# SPOT-CHECK LLM CALL
# Lightweight — one call, no 3-pass loop needed.
# Just asks: has this condition likely fired?
# ─────────────────────────────────────────────

_SPOT_CHECK_SYSTEM = """
You are Think AI's Condition Evaluator.
A user has provided an update about their business situation.
Your job is to assess whether a specific decision condition has likely fired,
is likely still clear, or is uncertain.

Be direct and specific. Do not hedge everything.
Return valid JSON only.
""".strip()


class _SpotCheckOutput(BaseModel):
    assessment:          Literal["likely_fired", "likely_clear", "uncertain"]
    reasoning:           str = Field(description="2–3 sentences explaining your assessment")
    recommended_action:  str = Field(description="One concrete action the user should take now")


async def _run_spot_check(
    condition:   ConditionRecord,
    user_update: str,
) -> _SpotCheckOutput:
    """Single LLM call to evaluate whether a condition has fired."""
    last_error: Exception | None = None

    user_message = f"""
Original decision: {condition.query_preview}

Condition type: {condition.kind.upper()}
Condition text: {condition.text}

User's current update: {user_update}

Has this condition fired, is it still clear, or is it uncertain?
""".strip()

    for attempt in range(1, _MAX_RETRIES + 1):
        try:
            response = await _get_client().chat.completions.create(
                model=_SPOT_CHECK_MODEL,
                messages=[
                    {"role": "system", "content": _SPOT_CHECK_SYSTEM + "\n\nRespond with valid JSON only. No markdown."},
                    {"role": "user",   "content": user_message},
                ],
                response_format={"type": "json_object"},
                temperature=0,
            )

            msg = response.choices[0].message
            raw = (msg.content or "").strip().lstrip("```json").lstrip("```").rstrip("```").strip()
            import json as _json
            return _SpotCheckOutput.model_validate(_json.loads(raw))

        except (APITimeoutError, APIStatusError) as e:
            status_code = getattr(e, "status_code", None)
            if status_code and status_code not in (429, 500, 502, 503, 504):
                raise
            last_error = e
            wait = (2 ** attempt) + random.uniform(0, 0.5)
            logger.warning(
                "Spot-check transient error | attempt=%d/%d | wait=%.1fs | %s",
                attempt, _MAX_RETRIES, wait, e,
            )
            await asyncio.sleep(wait)

        except Exception as e:
            last_error = e
            break

    raise RuntimeError("Spot-check failed after retries") from last_error


# ─────────────────────────────────────────────
# PUBLIC API
# ─────────────────────────────────────────────

async def register_conditions(
    company_id:  str,
    decision_id: str,
    query:       str,
    verdict:     VerdictBox,
) -> bool:
    """
    Called by main.py after format_for_ui() — as a fire-and-forget task.
    Extracts go/stop/review conditions from the VerdictBox and stores them.
    Safe to call multiple times for the same decision (deduplicates by ID).

    Parameters
    ----------
    company_id  : Tenant identifier.
    decision_id : Unique ID for this decision (from AuditTrail.query_hash).
    query       : The original decision text.
    verdict     : The VerdictBox from the RefinedDecision.

    Returns
    -------
    bool — True if written successfully.
    """
    new_records = _build_records_from_verdict(company_id, decision_id, query, verdict)

    if not new_records:
        logger.info(
            "No conditions to register | company_hash=%s | decision=%s",
            _company_hash(company_id)[:12], decision_id,
        )
        return True

    lock = _get_lock(company_id)
    try:
        await asyncio.wait_for(lock.acquire(), timeout=_LOCK_TIMEOUT_SEC)
    except asyncio.TimeoutError:
        logger.warning(
            "Conditions register lock timeout | company_hash=%s",
            _company_hash(company_id)[:12],
        )
        return False

    try:
        t0    = time.perf_counter()
        store = await _read_store(company_id) or _new_store(company_id)

        # Deduplicate — never double-register same condition
        existing_ids = {r.condition_id for r in store.records}
        to_add       = [r for r in new_records if r.condition_id not in existing_ids]

        store.records.extend(to_add)
        store.last_updated_utc = datetime.now(timezone.utc).isoformat()

        success = await _write_store(company_id, store)
        latency_ms = round((time.perf_counter() - t0) * 1000)

        logger.info(
            "✅ Conditions registered | company_hash=%s | decision=%s | "
            "added=%d | total=%d | latency_ms=%d",
            _company_hash(company_id)[:12],
            decision_id,
            len(to_add),
            len(store.records),
            latency_ms,
        )
        return success

    except Exception as e:
        logger.error(
            "register_conditions error | company_hash=%s | %s",
            _company_hash(company_id)[:12], e,
        )
        return False
    finally:
        lock.release()


async def get_active_conditions(company_id: str) -> ConditionReport:
    """
    Returns a structured report of all live conditions for a company.
    Automatically expires stale conditions as part of the read.
    Safe to call as frequently as needed — read-only except for expiry updates.

    Returns
    -------
    ConditionReport — always, even if empty.
    """
    t0    = time.perf_counter()
    store = await _read_store(company_id)

    if not store:
        now = datetime.now(timezone.utc).isoformat()
        return ConditionReport(
            company_id=company_id,
            total_active=0,
            total_fired=0,
            total_acknowledged=0,
            urgent=[],
            needs_review=[],
            go_conditions=[],
            generated_utc=now,
        )

    # Run expiry check on every record — update store if anything changed
    updated = [_check_expiry(r) for r in store.records]
    if any(r.status == "expired" for r in updated):
        store.records = updated
        store.last_updated_utc = datetime.now(timezone.utc).isoformat()
        # Non-blocking write — if it fails, next call will re-expire
        asyncio.create_task(_write_store(company_id, store))

    active  = [r for r in store.records if r.status == "active"]
    fired   = [r for r in store.records if r.status == "fired"]
    acked   = [r for r in store.records if r.status == "acknowledged"]

    # Sort by priority within each group
    urgent       = sorted(
        [r for r in fired if r.kind == "stop"],
        key=lambda r: r.fired_utc or r.created_utc,
    )
    needs_review = sorted(
        [r for r in fired if r.kind in ("review", "go")],
        key=lambda r: r.fired_utc or r.created_utc,
    )
    go_all       = sorted(
        [r for r in store.records if r.kind == "go" and r.status in ("active", "fired")],
        key=lambda r: r.status,   # fired first
    )

    latency_ms = round((time.perf_counter() - t0) * 1000)
    logger.info(
        "Conditions report | company_hash=%s | active=%d | fired=%d | latency_ms=%d",
        _company_hash(company_id)[:12],
        len(active), len(fired), latency_ms,
    )

    return ConditionReport(
        company_id=company_id,
        total_active=len(active),
        total_fired=len(fired),
        total_acknowledged=len(acked),
        urgent=urgent,
        needs_review=needs_review,
        go_conditions=go_all,
        generated_utc=datetime.now(timezone.utc).isoformat(),
    )


async def acknowledge_condition(
    company_id:   str,
    condition_id: str,
) -> bool:
    """
    User has seen the alert for a fired condition.
    Moves status from 'fired' → 'acknowledged'.
    Does NOT clear it — the condition is still real, just seen.

    Returns
    -------
    bool — True if found and updated.
    """
    return await _update_condition_status(
        company_id=company_id,
        condition_id=condition_id,
        new_status="acknowledged",
        timestamp_field="acknowledged_utc",
    )


async def clear_condition(
    company_id:   str,
    condition_id: str,
) -> bool:
    """
    User confirms a condition is no longer relevant (e.g. the risk passed).
    Moves status to 'cleared'.

    Returns
    -------
    bool — True if found and updated.
    """
    return await _update_condition_status(
        company_id=company_id,
        condition_id=condition_id,
        new_status="cleared",
        timestamp_field="cleared_utc",
    )


async def fire_condition(
    company_id:   str,
    condition_id: str,
) -> bool:
    """
    Manually mark a condition as fired (used by spot-check and marketplace.py).
    Moves status to 'fired'.

    Returns
    -------
    bool — True if found and updated.
    """
    return await _update_condition_status(
        company_id=company_id,
        condition_id=condition_id,
        new_status="fired",
        timestamp_field="fired_utc",
    )


async def _update_condition_status(
    company_id:      str,
    condition_id:    str,
    new_status:      ConditionStatus,
    timestamp_field: str,
) -> bool:
    """Internal helper — updates one condition's status field."""
    lock = _get_lock(company_id)
    try:
        await asyncio.wait_for(lock.acquire(), timeout=_LOCK_TIMEOUT_SEC)
    except asyncio.TimeoutError:
        return False

    try:
        store = await _read_store(company_id)
        if not store:
            return False

        for record in store.records:
            if record.condition_id == condition_id:
                record.status = new_status
                setattr(record, timestamp_field, datetime.now(timezone.utc).isoformat())
                record.last_checked_utc = datetime.now(timezone.utc).isoformat()
                store.last_updated_utc  = datetime.now(timezone.utc).isoformat()

                success = await _write_store(company_id, store)
                logger.info(
                    "✅ Condition updated | company_hash=%s | id=%s | status=%s",
                    _company_hash(company_id)[:12], condition_id, new_status,
                )
                return success

        logger.warning(
            "Condition not found | company_hash=%s | id=%s",
            _company_hash(company_id)[:12], condition_id,
        )
        return False

    except Exception as e:
        logger.error(
            "_update_condition_status error | company_hash=%s | %s",
            _company_hash(company_id)[:12], e,
        )
        return False
    finally:
        lock.release()


async def run_spot_check(
    company_id:   str,
    condition_id: str,
    user_update:  str,
    context:      UserContext | None = None,
) -> SpotCheckResult | None:
    """
    LLM-assisted condition evaluation.
    User provides a business update; the LLM assesses whether the condition
    has likely fired, is clear, or is uncertain.
    Updates the condition's status and stores the LLM's note.

    Parameters
    ----------
    company_id   : Tenant identifier.
    condition_id : The condition to check.
    user_update  : What the user knows right now about their business.
    context      : Optional UserContext for additional enrichment.

    Returns
    -------
    SpotCheckResult or None if condition not found.
    """
    # Find the condition
    store = await _read_store(company_id)
    if not store:
        return None

    target: ConditionRecord | None = None
    for r in store.records:
        if r.condition_id == condition_id:
            target = r
            break

    if target is None:
        logger.warning(
            "Spot-check: condition not found | company_hash=%s | id=%s",
            _company_hash(company_id)[:12], condition_id,
        )
        return None

    if target.status in ("cleared", "expired"):
        logger.info(
            "Spot-check skipped — condition already %s | id=%s",
            target.status, condition_id,
        )
        return None

    logger.info(
        "🔍 Spot-check | company_hash=%s | id=%s | kind=%s",
        _company_hash(company_id)[:12], condition_id, target.kind,
    )

    try:
        result = await _run_spot_check(target, user_update)
    except RuntimeError as e:
        logger.error("Spot-check LLM failed | %s", e)
        return None

    # Map assessment → new status
    status_map: dict[str, ConditionStatus] = {
        "likely_fired": "fired",
        "likely_clear": "active",
        "uncertain":    "active",
    }
    new_status = status_map[result.assessment]

    # Update stored record
    lock = _get_lock(company_id)
    try:
        await asyncio.wait_for(lock.acquire(), timeout=_LOCK_TIMEOUT_SEC)
    except asyncio.TimeoutError:
        logger.warning("Spot-check lock timeout | company_hash=%s",
                       _company_hash(company_id)[:12])
    else:
        try:
            store2 = await _read_store(company_id)
            if store2:
                for r in store2.records:
                    if r.condition_id == condition_id:
                        r.status            = new_status
                        r.last_checked_utc  = datetime.now(timezone.utc).isoformat()
                        r.spot_check_note   = result.reasoning
                        if new_status == "fired":
                            r.fired_utc = datetime.now(timezone.utc).isoformat()
                        break
                store2.last_updated_utc = datetime.now(timezone.utc).isoformat()
                await _write_store(company_id, store2)
        except Exception as e:
            logger.error("Spot-check write error | %s", e)
        finally:
            lock.release()

    logger.info(
        "✅ Spot-check done | company_hash=%s | id=%s | assessment=%s | new_status=%s",
        _company_hash(company_id)[:12], condition_id,
        result.assessment, new_status,
    )

    return SpotCheckResult(
        condition_id=condition_id,
        condition_text=target.text,
        kind=target.kind,
        user_update=user_update,
        assessment=result.assessment,
        reasoning=result.reasoning,
        recommended_action=result.recommended_action,
        new_status=new_status,
    )


async def request_reanalysis(
    company_id:   str,
    condition_id: str,
) -> bool:
    """
    Flags a condition for full re-analysis.
    Sets reanalysis_requested=True on the record.
    main.py / a background job can poll for these and re-run /decide.
    This is the hook for marketplace.py's automated re-triggering.

    Returns
    -------
    bool — True if flagged successfully.
    """
    lock = _get_lock(company_id)
    try:
        await asyncio.wait_for(lock.acquire(), timeout=_LOCK_TIMEOUT_SEC)
    except asyncio.TimeoutError:
        return False

    try:
        store = await _read_store(company_id)
        if not store:
            return False

        for record in store.records:
            if record.condition_id == condition_id:
                record.reanalysis_requested = True
                record.last_checked_utc     = datetime.now(timezone.utc).isoformat()
                store.last_updated_utc      = datetime.now(timezone.utc).isoformat()
                success = await _write_store(company_id, store)
                logger.info(
                    "🔁 Re-analysis requested | company_hash=%s | id=%s",
                    _company_hash(company_id)[:12], condition_id,
                )
                return success

        return False

    except Exception as e:
        logger.error("request_reanalysis error | %s", e)
        return False
    finally:
        lock.release()


async def get_reanalysis_queue(company_id: str) -> list[ConditionRecord]:
    """
    Returns all conditions where reanalysis_requested=True.
    Called by marketplace.py (and optionally by a background scheduler)
    to know which decisions need re-running through the full pipeline.
    """
    store = await _read_store(company_id)
    if not store:
        return []
    return [r for r in store.records if r.reanalysis_requested]


async def clear_all_conditions(company_id: str) -> bool:
    """
    Wipes all conditions for a company.
    Called alongside memory.clear_memory() for GDPR erasure.
    """
    lock = _get_lock(company_id)
    try:
        await asyncio.wait_for(lock.acquire(), timeout=_LOCK_TIMEOUT_SEC)
    except asyncio.TimeoutError:
        return False

    try:
        path = _store_path(company_id)
        if path.exists():
            await asyncio.to_thread(path.unlink)
            logger.info(
                "🗑️  Conditions cleared | company_hash=%s",
                _company_hash(company_id)[:12],
            )
            return True
        return False
    except Exception as e:
        logger.error("clear_all_conditions error | %s", e)
        return False
    finally:
        lock.release()


# ─────────────────────────────────────────────
# QUICK LOCAL TEST
# ─────────────────────────────────────────────

if __name__ == "__main__":
    import asyncio
    import json
    from router import route, UserContext
    from refiner import refine
    from output import format_for_ui

    async def _demo():
        company_id = "demo-co"
        query      = "Should we raise our prices by 20% next month?"
        ctx        = UserContext(
            industry="E-commerce",
            company_size="Series A",
            risk_appetite="Moderate",
        )

        print("── Step 1: Full pipeline ───────────────────────")
        plan     = await route(query, company_id, ctx)
        decision = await refine(query, plan, company_id, ctx)
        payload  = format_for_ui(decision, query, company_id)

        print(f"  Verdict: {payload.verdict_card.badge.label}")
        decision_id = decision.audit.query_hash[:16]

        print("\n── Step 2: Register conditions ─────────────────")
        ok = await register_conditions(
            company_id, decision_id, query, decision.verdict_box
        )
        print(f"  Registered: {ok}")

        print("\n── Step 3: Get active conditions ───────────────")
        report = await get_active_conditions(company_id)
        print(f"  Active: {report.total_active}")
        print(f"  Fired : {report.total_fired}")
        for r in report.go_conditions:
            print(f"  [GO]     {r.text[:60]}")
        for r in report.needs_review:
            print(f"  [REVIEW] {r.text[:60]}")
        for r in report.urgent:
            print(f"  [STOP ⚠️] {r.text[:60]}")

        # ── Test spot-check if any conditions exist ────────────────────────
        all_conditions = (
            report.go_conditions + report.needs_review + report.urgent
        )
        if all_conditions:
            target = all_conditions[0]
            print(f"\n── Step 4: Spot-check '{target.text[:40]}…' ──")
            result = await run_spot_check(
                company_id=company_id,
                condition_id=target.condition_id,
                user_update="Our latest data shows conversion rates dropped 12% this week.",
            )
            if result:
                print(f"  Assessment        : {result.assessment}")
                print(f"  Reasoning         : {result.reasoning}")
                print(f"  Recommended action: {result.recommended_action}")
                print(f"  New status        : {result.new_status}")

            print(f"\n── Step 5: Acknowledge condition ───────────────")
            ok = await acknowledge_condition(company_id, target.condition_id)
            print(f"  Acknowledged: {ok}")

    asyncio.run(_demo())